services:
  grist:
    image: gristlabs/grist:latest
   # env_file: .env
    volumes:
      - ./grist:/persist
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grist.loadbalancer.server.port=8484"
      - "traefik.http.routers.grist.rule=Host(`grist.edrazac.fr`)"
      - "traefik.http.routers.grist.tls.certresolver=myresolver"
      - "traefik.docker.network=frontend"

    networks:
      - frontend

networks:
  frontend:
    external: true
